export default {
    ACCOUNT_COMPLETION: "ACCOUNT_COMPLETION",
    ACCOUNT_DETAILS: "ACCOUNT_COMPLETION",
    REFRESH_TOKEN: "REFRESH_TOKEN",
    ACCOUNT_ACTIVATION: "ACCOUNT_ACTIVATION",
    PHONE_VERIFICATION: "PHONE_VERIFICATION",
    PASSWORD_UPDATE: "PASSWORD_UPDATE",
    PASSWORD_RESET: "PASSWORD_RESET",
};